// チャートページの銘柄定義。
// category: "fx" | "metal" | "crypto"。
// symbol      : TradingView のシンボル（チャート表示用）
// yahooSymbol : Yahoo Finance のシンボル（会員向けメール配信で現在値を取得するのに使う）
// lead        : 詳細ページ冒頭の説明文
export const CHART_PAIRS = [
  {
    id: "usdjpy",
    category: "fx",
    symbol: "FX:USDJPY",
    yahooSymbol: "USDJPY=X",
    name: "ドル円",
    pair: "USD/JPY",
    lead: "米ドル／日本円（USD/JPY）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。日本で最も取引量が多い通貨ペアで、日米の金利差や経済指標の影響を受けやすいのが特徴です。",
  },
  {
    id: "eurjpy",
    category: "fx",
    symbol: "FX:EURJPY",
    yahooSymbol: "EURJPY=X",
    name: "ユーロ円",
    pair: "EUR/JPY",
    lead: "ユーロ／日本円（EUR/JPY）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。欧州経済と日本の金融政策の影響を受ける、取引量の多いクロス円通貨ペアです。",
  },
  {
    id: "gbpjpy",
    category: "fx",
    symbol: "FX:GBPJPY",
    yahooSymbol: "GBPJPY=X",
    name: "ポンド円",
    pair: "GBP/JPY",
    lead: "英ポンド／日本円（GBP/JPY）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。クロス円の中でも値動きが大きく、ボラティリティを活かした短期売買で人気の通貨ペアです。",
  },
  {
    id: "chfjpy",
    category: "fx",
    symbol: "FX:CHFJPY",
    yahooSymbol: "CHFJPY=X",
    name: "CHF円",
    pair: "CHF/JPY",
    lead: "スイスフラン／日本円（CHF/JPY）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。安全資産とされるスイスフランと円の組み合わせで、リスクオフ局面の動向が注目される通貨ペアです。",
  },
  {
    id: "audjpy",
    category: "fx",
    symbol: "FX:AUDJPY",
    yahooSymbol: "AUDJPY=X",
    name: "AUD円",
    pair: "AUD/JPY",
    lead: "豪ドル／日本円（AUD/JPY）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。資源国通貨の代表格で、中国経済や商品市況の影響を受けやすい通貨ペアです。",
  },
  {
    id: "nzdjpy",
    category: "fx",
    symbol: "FX:NZDJPY",
    yahooSymbol: "NZDJPY=X",
    name: "NZD円",
    pair: "NZD/JPY",
    lead: "NZドル／日本円（NZD/JPY）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。乳製品など一次産品の市況とNZの金融政策の影響を受けるオセアニア通貨です。",
  },
  {
    id: "cadjpy",
    category: "fx",
    symbol: "FX:CADJPY",
    yahooSymbol: "CADJPY=X",
    name: "カナダドル円",
    pair: "CAD/JPY",
    lead: "カナダドル／日本円（CAD/JPY）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。原油価格との連動性が高い資源国通貨で、米国経済の動向にも左右されやすい通貨ペアです。",
  },
  {
    id: "zarjpy",
    category: "fx",
    symbol: "FX_IDC:ZARJPY",
    yahooSymbol: "ZARJPY=X",
    name: "南アフリカランド円",
    pair: "ZAR/JPY",
    lead: "南アフリカランド／日本円（ZAR/JPY）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。高金利通貨として知られる一方、資源価格や南アフリカの政情の影響を受けやすい通貨ペアです。",
  },
  {
    id: "tryjpy",
    category: "fx",
    symbol: "FX_IDC:TRYJPY",
    yahooSymbol: "TRYJPY=X",
    name: "トルコリラ円",
    pair: "TRY/JPY",
    lead: "トルコリラ／日本円（TRY/JPY）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。政策金利が高い一方でインフレと通貨安が続いており、値動きの荒さに注意が必要な通貨ペアです。",
  },
  {
    id: "mxnjpy",
    category: "fx",
    symbol: "FX_IDC:MXNJPY",
    yahooSymbol: "MXNJPY=X",
    name: "メキシコペソ円",
    pair: "MXN/JPY",
    lead: "メキシコペソ／日本円（MXN/JPY）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。高金利の新興国通貨として取引されており、米国経済や原油価格の影響を受けやすい通貨ペアです。",
  },
  {
    id: "eurusd",
    category: "fx",
    symbol: "FX:EURUSD",
    yahooSymbol: "EURUSD=X",
    name: "ユーロドル",
    pair: "EUR/USD",
    lead: "ユーロ／米ドル（EUR/USD）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。世界で最も取引量が多い通貨ペアで、ECBとFRBの金融政策の差が値動きの中心となります。",
  },
  {
    id: "gbpusd",
    category: "fx",
    symbol: "FX:GBPUSD",
    yahooSymbol: "GBPUSD=X",
    name: "ポンドドル",
    pair: "GBP/USD",
    lead: "英ポンド／米ドル（GBP/USD）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。「ケーブル」の通称で知られ、値動きの大きさから短期売買で好まれる主要通貨ペアです。",
  },
  {
    id: "audusd",
    category: "fx",
    symbol: "FX:AUDUSD",
    yahooSymbol: "AUDUSD=X",
    name: "豪ドル米ドル",
    pair: "AUD/USD",
    lead: "豪ドル／米ドル（AUD/USD）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。鉄鉱石など資源価格と中国経済の動向を映しやすい、代表的な資源国通貨ペアです。",
  },
  {
    id: "nzdusd",
    category: "fx",
    symbol: "FX:NZDUSD",
    yahooSymbol: "NZDUSD=X",
    name: "NZドル米ドル",
    pair: "NZD/USD",
    lead: "NZドル／米ドル（NZD/USD）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。豪ドルと似た値動きをしやすく、オセアニア経済と一次産品市況の影響を受ける通貨ペアです。",
  },
  {
    id: "usdchf",
    category: "fx",
    symbol: "FX:USDCHF",
    yahooSymbol: "USDCHF=X",
    name: "ドルスイスフラン",
    pair: "USD/CHF",
    lead: "米ドル／スイスフラン（USD/CHF）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。有事に買われやすいスイスフランの性質から、リスクオフ局面で下落しやすい通貨ペアです。",
  },
  {
    id: "usdcad",
    category: "fx",
    symbol: "FX:USDCAD",
    yahooSymbol: "USDCAD=X",
    name: "ドルカナダドル",
    pair: "USD/CAD",
    lead: "米ドル／カナダドル（USD/CAD）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。原油価格が上がるとカナダドル高（ペアは下落）になりやすい、資源連動型の通貨ペアです。",
  },
  {
    id: "eurgbp",
    category: "fx",
    symbol: "FX:EURGBP",
    yahooSymbol: "EURGBP=X",
    name: "ユーロポンド",
    pair: "EUR/GBP",
    lead: "ユーロ／英ポンド（EUR/GBP）の為替レートを、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。値幅が比較的落ち着いており、欧州域内の金融政策の差を見るのに適した通貨ペアです。",
  },
  {
    id: "gold",
    category: "metal",
    symbol: "OANDA:XAUUSD",
    yahooSymbol: "GC=F",
    name: "金（ゴールド）",
    pair: "XAU/USD",
    lead: "金（ゴールド）のドル建て価格（XAU/USD）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。インフレや地政学リスクの局面で買われやすい、代表的な安全資産です。",
  },
  {
    id: "platinum",
    category: "metal",
    symbol: "OANDA:XPTUSD",
    yahooSymbol: "PL=F",
    name: "プラチナ（白金）",
    pair: "XPT/USD",
    lead: "プラチナ（白金）のドル建て価格（XPT/USD）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。自動車の排ガス触媒など産業需要の比重が大きく、景気動向や南アフリカの供給情勢の影響を受けやすい貴金属です。",
  },
  {
    id: "silver",
    category: "metal",
    symbol: "OANDA:XAGUSD",
    yahooSymbol: "SI=F",
    name: "銀（シルバー）",
    pair: "XAG/USD",
    lead: "銀（シルバー）のドル建て価格（XAG/USD）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。投資需要と太陽光パネルなどの工業需要をあわせ持ち、金より値動きが大きくなりやすい貴金属です。",
  },
  {
    id: "palladium",
    category: "metal",
    symbol: "OANDA:XPDUSD",
    yahooSymbol: "PA=F",
    name: "パラジウム",
    pair: "XPD/USD",
    lead: "パラジウムのドル建て価格（XPD/USD）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。ガソリン車の排ガス触媒に使われる産業用貴金属で、供給がロシア・南アフリカに偏るため需給の影響を強く受けます。",
  },
  {
    id: "copper",
    category: "metal",
    symbol: "COMEX:HG1!",
    yahooSymbol: "HG=F",
    name: "銅（カッパー）",
    pair: "COMEX銅先物",
    lead: "銅（COMEX銅先物）の価格を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。電線や建設など幅広い産業で使われることから「ドクター・カッパー」と呼ばれ、世界景気の先行指標として注目されます。",
  },
  {
    id: "aluminum",
    category: "metal",
    symbol: "COMEX:ALI1!",
    yahooSymbol: "ALI=F",
    name: "アルミニウム",
    pair: "COMEXアルミ先物",
    lead: "アルミニウム（COMEXアルミ先物）の価格を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。自動車の軽量化や飲料缶などに使われる非鉄金属で、電力コストと中国の生産動向に左右されやすい商品です。",
  },
  {
    id: "btcjpy",
    category: "crypto",
    symbol: "BITFLYER:BTCJPY",
    yahooSymbol: "BTC-JPY",
    name: "ビットコイン円",
    pair: "BTC/JPY",
    lead: "ビットコインの円建て価格（BTC/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。24時間365日取引される暗号資産の代表格で、値動きの大きさが特徴です。",
  },
  {
    id: "ethjpy",
    category: "crypto",
    symbol: "BITFLYER:ETHJPY",
    yahooSymbol: "ETH-JPY",
    name: "イーサリアム円",
    pair: "ETH/JPY",
    lead: "イーサリアムの円建て価格（ETH/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。スマートコントラクト基盤の代表格で、ビットコインに次ぐ時価総額を持つ暗号資産です。",
  },
  {
    id: "xrpjpy",
    category: "crypto",
    symbol: "BITFLYER:XRPJPY",
    yahooSymbol: "XRP-JPY",
    name: "XRP円",
    pair: "XRP/JPY",
    lead: "XRP（リップル）の円建て価格（XRP/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。国際送金分野での活用が注目される、日本でも取引量の多い暗号資産です。",
  },
  {
    id: "dogejpy",
    category: "crypto",
    symbol: "BINANCE:DOGEJPY",
    yahooSymbol: "DOGE-JPY",
    name: "ドージコイン円",
    pair: "DOGE/JPY",
    lead: "ドージコイン（DOGE）の円建て価格（DOGE/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。ミームコインの代表格で、SNSや著名人の発言をきっかけに大きく動くことがある暗号資産です。",
  },
  {
    id: "ltcjpy",
    category: "crypto",
    symbol: "BINANCE:LTCJPY",
    yahooSymbol: "LTC-JPY",
    name: "ライトコイン円",
    pair: "LTC/JPY",
    lead: "ライトコイン（LTC）の円建て価格（LTC/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。ビットコインから派生した歴史の長い暗号資産で、送金の速さと手数料の安さが特徴です。",
  },
  {
    id: "soljpy",
    category: "crypto",
    symbol: "BINANCE:SOLJPY",
    yahooSymbol: "SOL-JPY",
    name: "ソラナ円",
    pair: "SOL/JPY",
    lead: "ソラナ（SOL）の円建て価格（SOL/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。処理速度の速さと手数料の安さを特徴とするブロックチェーンで、時価総額上位に位置する暗号資産です。",
  },
  {
    id: "bnbjpy",
    category: "crypto",
    symbol: "BINANCE:BNBJPY",
    yahooSymbol: "BNB-JPY",
    name: "BNB円",
    pair: "BNB/JPY",
    lead: "BNBの円建て価格（BNB/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。大手取引所バイナンスのエコシステムで使われる暗号資産で、時価総額上位を維持しています。",
  },
  {
    id: "adajpy",
    category: "crypto",
    symbol: "BINANCE:ADAJPY",
    yahooSymbol: "ADA-JPY",
    name: "カルダノ円",
    pair: "ADA/JPY",
    lead: "カルダノ（ADA）の円建て価格（ADA/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。学術研究に基づく開発体制で知られるブロックチェーンの独自トークンです。",
  },
  {
    id: "linkjpy",
    category: "crypto",
    symbol: "BINANCE:LINKJPY",
    yahooSymbol: "LINK-JPY",
    name: "チェーンリンク円",
    pair: "LINK/JPY",
    lead: "チェーンリンク（LINK）の円建て価格（LINK/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。ブロックチェーンに外部データを提供するオラクル基盤の代表格として知られる暗号資産です。",
  },
  // AVAX/JPY は掲載できない。TradingView に円建てのシンボルが存在しないため
  // （シンボル検索APIで全取引所ヒットなし）、チャートが「このシンボルは存在しません」になる。
  // 円建てが追加されたら戻せる。
  {
    id: "bchjpy",
    category: "crypto",
    symbol: "BINANCE:BCHJPY",
    yahooSymbol: "BCH-JPY",
    name: "ビットコインキャッシュ円",
    pair: "BCH/JPY",
    lead: "ビットコインキャッシュ（BCH）の円建て価格（BCH/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。ビットコインから分岐した暗号資産で、送金手数料の安さを特徴としています。",
  },
  {
    id: "trxjpy",
    category: "crypto",
    symbol: "BINANCE:TRXJPY",
    yahooSymbol: "TRX-JPY",
    name: "トロン円",
    pair: "TRX/JPY",
    lead: "トロン（TRX）の円建て価格（TRX/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。手数料の安さを背景にステーブルコインの送金基盤として使われることが多い暗号資産です。",
  },
  {
    id: "xlmjpy",
    category: "crypto",
    symbol: "BITFLYER:XLMJPY",
    yahooSymbol: "XLM-JPY",
    name: "ステラルーメン円",
    pair: "XLM/JPY",
    lead: "ステラルーメン（XLM）の円建て価格（XLM/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。個人向けの少額送金を想定して設計されたブロックチェーンの暗号資産です。",
  },
  {
    // DOT/JPY は BINANCE 等には無いが KRAKEN にはある。以前に掲載を取りやめた経緯があるため、
    // 取引所を変えて復活させた。シンボルを変えるときは symbol-search API で実在を確認すること。
    id: "dotjpy",
    category: "crypto",
    symbol: "KRAKEN:DOTJPY",
    yahooSymbol: "DOT-JPY",
    name: "ポルカドット円",
    pair: "DOT/JPY",
    lead: "ポルカドット（DOT）の円建て価格（DOT/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。複数のブロックチェーンを相互接続する構想で知られるプロジェクトの暗号資産です。",
  },
  {
    id: "shibjpy",
    category: "crypto",
    symbol: "BINANCE:SHIBJPY",
    yahooSymbol: "SHIB-JPY",
    name: "柴犬コイン円",
    pair: "SHIB/JPY",
    lead: "柴犬コイン（SHIB）の円建て価格（SHIB/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。ドージコインに続くミームコインの代表格で、1枚あたりの単価が非常に小さいのが特徴です。",
  },
  {
    id: "monajpy",
    category: "crypto",
    symbol: "BITFLYER:MONAJPY",
    yahooSymbol: "MONA-JPY",
    name: "モナコイン円",
    pair: "MONA/JPY",
    lead: "モナコイン（MONA）の円建て価格（MONA/JPY）を、1分足・30分足・日足の3つの時間軸でリアルタイム表示しています。日本発の暗号資産として知られ、国内取引所を中心に売買されています。",
  },
];

export const FX_PAIRS = CHART_PAIRS.filter((p) => p.category === "fx");
export const METAL_PAIRS = CHART_PAIRS.filter((p) => p.category === "metal");
export const CRYPTO_PAIRS = CHART_PAIRS.filter((p) => p.category === "crypto");

/**
 * 詳細ページ（/charts/<id>/）を検索エンジンに載せない銘柄。
 *
 * 詳細ページはチャートウィジェットと短いリード文だけで構成されるため、掲載銘柄を
 * 増やすほど中身の薄いページが積み上がる。会員が表示銘柄を選べるようにするために
 * 追加したこの24銘柄は、一覧ページ（/fx/・/metals/・/crypto/）には従来どおり出しつつ、
 * 詳細ページだけ noindex にしてサイトマップからも外す。
 * もともと掲載していた14銘柄は、これまでどおり検索対象のまま。
 */
const NOINDEX_DETAIL_IDS = new Set([
  // FX
  "cadjpy", "zarjpy", "tryjpy", "mxnjpy",
  "eurusd", "gbpusd", "audusd", "nzdusd", "usdchf", "usdcad", "eurgbp",
  // 貴金属
  "palladium", "copper", "aluminum",
  // 暗号資産
  "soljpy", "bnbjpy", "adajpy", "linkjpy", "bchjpy",
  "trxjpy", "xlmjpy", "dotjpy", "shibjpy", "monajpy",
]);

/** その銘柄の詳細ページを検索エンジンに載せるか */
export function isDetailIndexable(id) {
  return !NOINDEX_DETAIL_IDS.has(id);
}
